[package]
name = 'clarabel'
version = '0.5.1'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'clarabel'

[dependencies]
extendr-api = '0.4.0'
clarabel = {version = '0.5.1', features = [ 'sdp-r' ]}
lazy_static = "1.4.0"
regex = "1.8.4"
