[package]
name = 'clarabel'
version = '0.4.1'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'clarabel'

[dependencies]
extendr-api = '0.4.0'
clarabel = '0.4.1'
lazy_static = "1.4.0"
regex = "1.7.3"
